### ISSUE TITLE
Speeding up contains_full_disk.

### ISSUE THREAD

**Issue by wafels** [heliohackweek/AIA_acceleration#2]
I have a version of `contains_full_disk` that does not test every pixel coordinate.  It's a bit janky, but it passes the existing tests.  It uses the edges of the map to test if the map is a rectangle that has edges that are least a solar diameter in length assuming that the Sun is centered in the image.  This is vastly fewer pixels than currently.  The code is at https://github.com/wafels/sunpy/blob/faster_full_disk/sunpy/map/maputils.py#L127 .

**Comment by cbard** [comment]
Ok, this is a good start! Are you planning to push this to sunpy? Otherwise, I'll plan to copy this `contains_full_disk` code (with proper attribution to you) and start testing it in my local `register` function.

**Comment by wtbarnes** [comment]
Will this be a PR to sunpy soon? 😜

**Comment by wafels** [comment]
I would copy the code in to the hack week repository at the moment. It’ll
take a while for this to be in the released version of sunpy. 🤪

**Comment by wafels** [comment]
I made a PR to SunPy with this fix.  It's much faster.
